query GenerateWorkerPayment($query: GenerateWorkerPaymentQueryInput!) {
  generateWorkerPayment(query: $query) {
    payment {
      paymentHoursBasic
      surcharges {
        paymentHoursBasicHoliday
        paymentHoursNightHoliday
        paymentHoursExtraHoliday
        paymentHoursExtra
        paymentHoursNight
      }
    }
    totalizer {
      hoursNightBasic
      hoursNightHoliday
      hoursWorkedBasic
      hoursWorkedBasicHoliday
      hoursWorkedExtraBasic
      hoursWorkedExtraHoliday
      hoursWorkedTotal
    }
    details {
    	day
      registers {
        start
        end
      }
    }
  }
}