query GenerateWorkerPayment($query: GenerateWorkerPaymentQueryInput!) {
  generateWorkerPayment(query: $query) {
    payment {
      paymentHoursBasic
      surcharges {
        paymentHoursNightHoliday
        paymentHoursExtraHoliday
        paymentHoursExtra
        paymentHoursNight
      }
    }
    details {
    	day
      hoursWorkedTotal
      hoursNight
      registers {
        start
        end
      }
    }
  }
}