query GetListWorkerMarkTime($query: WorkerMarkTimeQuery!) {
  getListWorkerMarkTime(query: $query) {
    dateRegister
    identification
    type
    reason
    picture
    created
    modified
    entity
  }
}
