query GetPaymentTemplate {
  getPaymentTemplate {
    extraHourHoliday
    intervalNonNight { since until}
    baseHourDay
    baseHourHoliday
    nocturnHourNormalDay
    nocturnHourHoliday
    extraHourNormalDay
    hoursMinimum 
  }
}
